In [1]:
!pip install gym

In [2]:
# import all necessary modules
import numpy as np
import random
import time
import gym
from IPython.display import clear_output

In [4]:
env = gym.make("FrozenLake-v1")

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [6]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

qtable = np.zeros((state_space_size, action_space_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [9]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()

    done = False # is episode over?
    rewards_current_episode = 0 # rewards of the current episode

    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0, 1) # should the agent explore or explout
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample() # sample an action randomly

        new_state, reward, done, info = env.step(action)

        #update Q-table for Q(s,a)
        qtable[state, action] = qtable[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(qtable[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q-table
print("\n\n********Q-table********\n")
print(qtable)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


********Average reward per thousand episodes********

1000 :  0.05000000000000004
2000 :  0.19800000000000015
3000 :  0.4270000000000003
4000 :  0.5510000000000004
5000 :  0.6060000000000004
6000 :  0.6570000000000005
7000 :  0.6200000000000004
8000 :  0.6750000000000005
9000 :  0.6780000000000005
10000 :  0.6690000000000005


********Q-table********

[[0.53843164 0.49937885 0.50517311 0.49658867]
 [0.36815093 0.21399152 0.24190578 0.4127176 ]
 [0.31965402 0.31085059 0.26935947 0.28272822]
 [0.10511061 0.10295086 0.05566548 0.26573258]
 [0.55004829 0.4963601  0.46083616 0.36184933]
 [0.         0.         0.         0.        ]
 [0.18528105 0.15264014 0.13653257 0.10029565]
 [0.         0.         0.         0.        ]
 [0.39326124 0.39310892 0.38932816 0.59735077]
 [0.4323625  0.6625839  0.43439908 0.37499454]
 [0.61582334 0.29908613 0.17694636 0.39461137]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.32177569 0.48706776 0.7417495  